### ISSUE TITLE
在使用PhaseTank的一个问题

### ISSUE THREAD

**Issue by wangyuhu123** [QingliGuo/PhaseTank#1]
作者您好，我在使用该软件时遇到了一些问题，我的命令是这样：
PhaseTank_v1.0.pl --genome ${genome} --lib ${input}/Dla_BaMV_1_fastp_fillter_N_rename.fasta,${input}/Dla_BaMV_2_fastp_fillter_N_rename.fasta,${input}/Dla_BaMV_3_fastp_fillter_N_rename.fasta

报错截图如下：
![报错截图](https://github.com/QingliGuo/PhaseTank/assets/70244560/b995c0ce-d48f-42db-8277-200d93725063)
我无法解决这个问题。

**Comment by QingliGuo** [comment]
不像phasetank的问题，你查一下你是否在运行目录下有写入权限。

**Comment by wangyuhu123** [comment]
> 没有pha​​setank的问题，你查一下你是否在运行目录下有读取权限。

我以root身份运行的，按理说不存在权限的问题吧？而且他虽然这步报错了，但是还是建了文件夹，只是后面还有一些错误，我给您看一下完整的报错截图
![报错](https://github.com/QingliGuo/PhaseTank/assets/70244560/f1df0917-cefb-4265-9443-c4a70ec68dd8)

**Comment by QingliGuo** [comment]
你的fasta文件格式有问题，ID行里面需要一个'_x'把reads名称和reads数量隔开。你参考我的文件看看。

**Comment by wangyuhu123** [comment]
> 你的fasta文件格式有问题，ID行里面需要一个'_x'把reads名称和reads数量隔开。你参考我的文件看看

感谢您的回复，我等下试试。我还是有一个疑问，每一个ID不都对应一个read吗？那reads数量不都等于1吗

**Comment by wangyuhu123** [comment]
> 



> 你的fasta文件格式有问题，ID行里面需要一个'_x'把reads名称和reads数量隔开。你参考我的文件看看。

您的意思是说unique read的数量吗

**Comment by wangyuhu123** [comment]
> 你的fasta文件格式有问题，ID行里面需要一个'_x'把reads名称和reads数量隔开。你参考我的文件看看。
您的意思是说该reads在这个文库中有多少重复吗

**Comment by QingliGuo** [comment]
是的

**Comment by wydsqgg** [comment]
您好，我同样遇见了这个问题的，我现在修改我的fa文件格式为>V350286861L1C001R00100001459/1 _x
AAGTCGTGAGGGTTCAAGTCCCTCTATCCCCACT,还是出现同样的报错。

**Comment by QingliGuo** [comment]
你的'_x'前面有个多余的空格

**Comment by wydsqgg** [comment]
> 你的'_x'前面有个多余的空格

![image](https://github.com/user-attachments/assets/c92cac53-c9d9-4897-9b24-68eb15582199)
我删掉空格还是出现了一样的报错。

**Comment by QingliGuo** [comment]
Perhaps remove '/' and try again.
